### PR TITLE
Add pagination based on nextLink property

### PR DESCRIPTION
**Pull request by jkroepke**
Ref: https://github.com/grafana/grafana-infinity-datasource/discussions/783

This PR implements a pagination option based on a property inside the json body.

The pagination option fully works here, however merging the result is still an issue:

Example:

Page 1

```json
{
  "@odata.count": 500,
  "@odata.nextLink": "<full-url-with-specific page params>",
  "value": "[{...data...}]",
}
```

Page 2

```json
{
  "@odata.count": 234,
  "value": "[{...data...}]",
}
```

On second page, the nextLink is missing, because there is no next link. If there is an option todo the merge based on a context, for example `$.value`, let me know.

### CODE REVIEW

**Comment by jkroepke** [comment]
Is it fine, that the merging of results may not work yet and can be handle in a separate PR?

**Comment by jkroepke** [comment]
> merging of the results

this that case, I may need assistent here

**Comment by jkroepke** [comment]
> anyhow, we can't merge this without "merging of the results".

I looked deeper into this issue. In general, merging works fine, if a Root is given at parsing options.

My issue here is that I my API has a boolean field, we can have true/false/null. If null, infinity fall back to string. But there row with an boolean, it turns into an error, because bool and string are different.

**Comment by jkroepke** [comment]
@yesoreyeram Can I help here? This PR currently blocks us in usage of Azure Cost API and Microsoft 365 Graph APIs.

**Comment by jkroepke** [comment]
Hey @yesoreyeram 

I have provide a new unit test which allow to creates mock responses. I hope it's sufficient.

**Comment by jkroepke** [comment]
Hey @yesoreyeram, did you find time todo an review here?

**Comment by jkroepke** [comment]
I will do a rebase after the next review cycle.

**Comment by jkroepke** [comment]
Hey @yesoreyeram

any new about this?

**Comment by jpike88** [comment]
Well now I know the health of the code in this project. I'm going to ditch this as a data source and move to using Skyvia or some ETL methodology to populate a db

**Comment by kcsuden** [comment]
Does any of this functionality work yet? I am using JSONata to try to grab the pagination cursor from the hubspot api like so

Screenshot 2025-08-08 at 2 54 04 PM

However, the pagination logic doesn't work. For Replace URL, the requests are being made, but they are clearly just using the original query, since all the subsequent outputs are the same.


Screenshot 2025-08-08 at 3 01 29 PM

For Query Param, the query parameter is being added **into the content** of the response, but the content of the response is not being used for the next query url


Screenshot 2025-08-08 at 3 04 29 PM

**Pull request closed without merging**
